trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: "/"
    output_location: "dist"
    api_location: ""  # Leave blank if you're not using Azure Functions
    azure_static_web_apps_api_token: $(deployment_token)
  displayName: 'Deploy to Azure Static Web Apps'
